### PR TITLE
Spanish-Spain translation Disposable.php

### PR DESCRIPTION
**Pull request by avs-code**
Spanish-Spain translation

### CODE REVIEW

**Comment by FatihKoz** [comment]
Maybe we should separate Spanish and Portugal, both in v7 core and my addons 'cause they have some differences when used in different countries.

pt-pt // For Portuguese used as in Portugal
pt-br // For Portuguese used as in Brazil (or South America)

es-es // Pure Spain Spanish
es-ag // Argentina version
es-mx // Mexico version

and so on, if this change gets to v7 core, then we can have it in my addons/theme too. Holding this open a little bit to clarify things ;)

**Comment by avs-code** [comment]
> Maybe we should separate Spanish and Portugal, both in v7 core and my addons 'cause they have some differences when used in different countries.
> 
> pt-pt // For Portuguese used as in Portugal pt-br // For Portuguese used as in Brazil (or South America)
> 
> es-es // Pure Spain Spanish es-ag // Argentina version es-mx // Mexico version
> 
> and so on, if this change gets to v7 core, then we can have it in my addons/theme too. Holding this open a little bit to clarify things ;)

Yes, @maco suggested that. if it can be done better.

The further a language moves away from its country of origin, the more its own words change, British English is no longer the same as Australian English. Imagine South America with so many cultures. I also heard that Brazilian Portuguese is becoming less and less like Portuguese.

**Comment by FatihKoz** [comment]
Yeah, technically speaking it is just renaming the language folder to have different versions of it. Nothing more

Like instead of having only `es` for Spanish, we need to have `es-es` and `es-mx` when needed. I am using a custom English translation myself.

Named the folder `en-dispo` :) and using that exact name at my env.php to have it work. Since there are no other settings or changes needed, it was the best solution I find for my own custom wording and making life easier to update v7 when needed.

Same logic can be used for Portuguese as it is really different at Brazil / South America from the original one spoken at Portugal.

**Comment by FatihKoz** [comment]
And he is not `@maco` here at GitHub, proper username is @macofallico if you want to tag him ;)

**Comment by maco** [comment]
oh *that's* why I'm confused. I was like "commenting on translations is a thing I would do, but I don't know what this software is"

**Comment by FatihKoz** [comment]
Sorry for that :) "Maco" is the name we are used to use in our discord server, tagging may cause issues when communications become cross-platform.

The software is related with flight simulation and "virtual airlines" by the way.

**Comment by avs-code** [comment]
oh, I've summoned someone from the outside, I'm so sorry.

**Comment by avs-code** [comment]
Where we separate this in nabeel repo?

**Comment by avs-code** [comment]
Approve es-es pull-request #3

**Pull request closed without merging**
